
%plotHistogram('histogram_data/base_hist.dat', 'histogram_images/base_hist.png', 'Base Image Histogram');

fileNames = {'base_hist', 'scale_hist', 'scale_range_hist', 'inv_hist', ...
    'exp_hist', 'exp_equ_hist', 'log_hist', 'log_equ_hist', ...
    'gamma/gamma0.13_hist', 'gamma/gamma0.13_equ_hist',...
    'gamma/gamma0.25_hist', 'gamma/gamma0.25_equ_hist',...
    'gamma/gamma0.50_hist', 'gamma/gamma0.50_equ_hist',...
    'gamma/gamma1.00_hist', 'gamma/gamma1.00_equ_hist',...
    'gamma/gamma2.00_hist', 'gamma/gamma2.00_equ_hist',...
    'gamma/gamma4.00_hist', 'gamma/gamma4.00_equ_hist',...
    'gamma/gamma8.00_hist', 'gamma/gamma8.00_equ_hist',...
    };

plotTitles = {'Base', 'Divide By 2', 'Full Scale', 'Invert', ...
    'Exponential', 'Equalized Exponential', 'Logarithm', 'Equalized Logarithm', ...
    'Gamma = 0.125', 'Equalized Gamma = 0.125', ...
    'Gamma = 0.25', 'Equalized Gamma = 0.25', ...
    'Gamma = 0.5', 'Equalized Gamma = 0.5', ...
    'Gamma = 1', 'Equalized Gamma = 1', ...
    'Gamma = 2', 'Equalized Gamma = 2', ...
    'Gamma = 4', 'Equalized Gamma = 4', ...
    'Gamma = 8', 'Equalized Gamma = 8', ...
    };

for i=1:length(fileNames)
    
    histFileName = strcat('histogram_data/', fileNames(i), '.dat');
    outFileName = strcat('histogram_images/', fileNames(i), '.png');
    plotName = strcat(plotTitles(i), ' Image Histogram');
    
    plotHistogram(char(histFileName), char(outFileName), char(plotName));
end